name: HMS CI/CD Pipeline

on:
  push:
    branches:
      - main  # Deploy only when main branch is updated
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test # Make sure your test script is correct

      - name: Build Project
        run: npm run build

      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main' && success()
        run: |
          npm install -g vercel
          vercel link --token ${{ secrets.VERCEL_TOKEN }}
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
